"""VITHIA DAISY ECA curriculum (training-candidate corpus lineage; NOT the E0-E4 evaluation datasets).

World ("CA dodge", 1P): an ECA rule evolves a hazard row of width W on a ring; row t arrives at the
ship row at decision t. The ship at x chooses LEFT / STAY / RIGHT (ECA-native control alphabet, not
Atari's). It is hit if the arriving row has a 1 at its new x. Action sequences are an intervention
layer on an environment generated by the rule; they do not form or alter the rule.

Exact simulator state = (rule, current hazard row, x). The hazard is action-independent, so action
sequences reaching the same x at the same decision boundary are provably the same state and merge.
"""
from __future__ import annotations

import hashlib
import json
import math
import random

from src.kernels.eca import eca_step

W, T_TRAJ, H_ORACLE, H_A4 = 16, 32, 8, 2
ACTIONS = ("LEFT", "STAY", "RIGHT")
DX = {"LEFT": -1, "STAY": 0, "RIGHT": 1}
ICS = {"single": None, "rand1": 11, "rand2": 12, "rand3": 13}
IC_HOLDOUT = "rand3"                        # whole IC family held out for evaluation
STARTS = (W // 4, W // 2, 3 * W // 4)
DELTAG_STATE = "NOT_COMPUTED"               # model-free rows never carry ΔG*


def cid(obj) -> str:
    return "sha256:" + hashlib.sha256(json.dumps(obj, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


# ---------- D0 rule atomization ----------
def truth_table(rule: int) -> list[int]:
    return [(rule >> j) & 1 for j in range(8)]


def reflect(rule: int) -> int:
    return sum(((rule >> (4 * l + 2 * c + r)) & 1) << (4 * r + 2 * c + l) for l in (0, 1) for c in (0, 1) for r in (0, 1))


def complement(rule: int) -> int:
    return sum((1 - ((rule >> (4 * (1 - l) + 2 * (1 - c) + (1 - r))) & 1)) << (4 * l + 2 * c + r)
               for l in (0, 1) for c in (0, 1) for r in (0, 1))


def orbit(rule: int) -> list[int]:
    return sorted({rule, reflect(rule), complement(rule), reflect(complement(rule))})


def rule_atom(rule: int) -> dict:
    tt = truth_table(rule)
    return {"rule_id": rule, "truth_table_lsb_first": tt, "canonical_rule_bytes_hex": bytes([rule]).hex(),
            "rule_hash": cid({"eca_rule": rule, "truth_table": tt}), "orbit": orbit(rule), "orbit_rep": min(orbit(rule)),
            "lambda": sum(tt) / 8, "wolfram_class": "NOT_PROVIDED (no sourced label)"}


# ---------- split policy (family-level, never row-level) ----------
def split_of(rule: int, ic: str) -> str:
    if ic == IC_HOLDOUT:
        return "test_ic_holdout"
    b = int(hashlib.sha256(f"DAISY|orbit|{min(orbit(rule))}".encode()).hexdigest(), 16) % 10
    return "train" if b < 7 else ("validation" if b < 9 else "test_rule_holdout")


# ---------- D1 transitions ----------
def initial(ic: str) -> tuple[int, ...]:
    if ICS[ic] is None:
        return tuple(1 if i == W // 2 else 0 for i in range(W))
    rng = random.Random(ICS[ic])
    return tuple(rng.randrange(2) for _ in range(W))


def row_hash(row) -> str:
    return cid({"row": list(row)})


def trajectory(rule: int, ic: str, T: int = T_TRAJ) -> list[tuple[int, ...]]:
    rows = [initial(ic)]
    for _ in range(T):
        rows.append(tuple(eca_step(list(rows[-1]), rule)))
    return rows


def transition_rows(rule: int, ic: str) -> list[dict]:
    rows, seen, out = trajectory(rule, ic), set(), []
    for t in range(len(rows) - 1):
        key = (rows[t], rows[t + 1])
        dup = key in seen
        seen.add(key)
        out.append({"corpus_id": "VITHIA_DAISY_ECA_RULE_CORPUS_V1", "split": split_of(rule, ic), "rule_id": rule,
                    "initial_condition_id": ic, "step": t, "state_t": list(rows[t]), "state_t_hash": row_hash(rows[t]),
                    "state_t_plus_1": list(rows[t + 1]), "state_t_plus_1_hash": row_hash(rows[t + 1]),
                    "duplicate_of_earlier_transition": dup})
    return out


# ---------- D2 control graph (exact, transposition-merged) ----------
def state_id(rule: int, row, x: int) -> str:
    return cid({"world": "ca_dodge_v1", "rule": rule, "row": list(row), "x": x, "W": W})


def graph(rule: int, rows, t0: int, x0: int, H: int) -> dict:
    """Layered DP over depth; per layer the nodes are distinct x (hazard is action-independent)."""
    layers = [{x0: 1}]
    for d in range(1, H + 1):
        arriving = rows[t0 + d]
        nxt = {}
        for x, n in layers[-1].items():
            for a in ACTIONS:
                nx = min(max(x + DX[a], 0), W - 1)
                if arriving[nx] == 0:
                    nxt[nx] = nxt.get(nx, 0) + n
        layers.append(nxt)
    return {"layers": layers}


def safe_paths_from(rule, rows, t, x, H) -> int:
    return sum(graph(rule, rows, t, x, H)["layers"][-1].values()) if H > 0 else 1


def action_stats(rule: int, rows, t: int, x: int, H: int) -> dict:
    out = {}
    for a in ACTIONS:
        nx = min(max(x + DX[a], 0), W - 1)
        hit = rows[t + 1][nx] == 1
        safe = 0 if hit else safe_paths_from(rule, rows, t + 1, nx, H - 1)
        out[a] = {"successor_x": nx, "collision": hit, "safe_paths": safe, "survivable": safe > 0,
                  "safe_fraction": safe / 3 ** (H - 1), "successor_state_id": state_id(rule, rows[t + 1], nx)}
    return out


def entropy_bits(counts) -> float:
    tot = sum(counts)
    return -sum(c / tot * math.log2(c / tot) for c in counts if c) if tot else 0.0


def action_rows(rule: int, ic: str) -> list[dict]:
    rows = trajectory(rule, ic, H_ORACLE + 1)
    out = []
    for x in STARTS:
        g = graph(rule, rows, 0, x, H_ORACLE)
        st = action_stats(rule, rows, 0, x, H_ORACLE)
        best = max(v["safe_fraction"] for v in st.values())
        fr = sorted((v["safe_fraction"] for v in st.values()), reverse=True)
        opt = sorted(a for a, v in st.items() if v["safe_fraction"] == best and v["survivable"])
        a4 = action_stats(rule, rows, 0, x, H_A4)
        tot = sum(v["safe_paths"] for v in a4.values())
        sid = state_id(rule, rows[0], x)
        for a in ACTIONS:
            out.append({
                "corpus_id": "VITHIA_DAISY_ECA_ACTION_CORPUS_V1", "split": split_of(rule, ic), "rule_id": rule,
                "initial_condition_id": ic, "state_id": sid, "parent_state_id": None,
                "successor_state_id": st[a]["successor_state_id"], "step": 0, "trajectory_id": cid({"rule": rule, "ic": ic, "x0": x}),
                "state": {"row": list(rows[0]), "x": x, "W": W},
                "history_atoms": "NOT_APPLICABLE (t=0)",
                "public_anticube": {"ship": {"identity": "SELF", "safety": "UNSAFE" if rows[1][x] else "SAFE"},
                                    "hazard_cells": {"identity": "NONSELF", "safety": "UNSAFE"}},
                "constraint_field": {"next_row": list(rows[1])},
                "path_distribution": {"horizon": H_A4, "mass_by_first_action": {k: (v["safe_paths"] / tot if tot else None) for k, v in a4.items()},
                                      "label": f"public limited-lookahead (H={H_A4}) distribution; oracle horizon is {H_ORACLE}; not ΔG*"},
                "legal_actions": list(ACTIONS), "action": a, "action_sequence": [a], "first_action": a,
                "action_equivalence_class": cid({"state": sid, "successor_x": st[a]["successor_x"]}),
                "collision": st[a]["collision"], "survivable": st[a]["survivable"], "safe_fraction": st[a]["safe_fraction"],
                "terminal": st[a]["collision"],
                "reachable_state_count": len(g["layers"][-1]),
                "reachable_state_entropy_bits": round(entropy_bits(list(g["layers"][-1].values())), 6),
                "optimal_action_set": opt, "decision_margin": round(fr[0] - fr[1], 6),
                "regret": round(best - st[a]["safe_fraction"], 6),
                "U_star": 0.0 if st[a]["survivable"] else 1.0, "H_norm": "NOT_COMPUTED", "G_star": "NOT_COMPUTED",
                "delta_G_star": DELTAG_STATE, "delta_g_definition_id": None,
                "provider": "NOT_APPLICABLE", "probabilities": "NOT_APPLICABLE",
                "oracle_horizon": H_ORACLE})
    return out


# ---------- D4/D5 context arms (ECA) ----------
def arm_context(row: dict, arm: str, other: dict | None = None, seed: int = 0) -> dict:
    base = {"row": row["state"]["row"], "x": row["state"]["x"], "W": W, "legal_actions": list(ACTIONS)}
    hist = {"rule_truth_table": truth_table(row["rule_id"])}
    full = {**base, "history": hist, "anticube": row["public_anticube"], "path_distribution": row["path_distribution"]}
    if arm == "A0_RAW":
        return base
    if arm == "A1_VITACONTEXT":
        return {**base, "history": hist}
    if arm == "A2_ANTICUBE":
        return {**base, "history": hist, "anticube": row["public_anticube"]}
    if arm in ("A4_PATH_DISTRIBUTION", "A5_VITA01_FULL"):
        return full
    if arm == "NULL_METADATA":
        return {**base, "history": None, "anticube": None, "path_distribution": None}
    if arm == "SHUFFLED_HISTORY":
        tt = hist["rule_truth_table"][:]
        random.Random(seed).shuffle(tt)
        return {**full, "history": {"rule_truth_table": tt}}
    if arm == "UNRELATED_HISTORY":
        return {**full, "history": {"rule_truth_table": truth_table(other["rule_id"])}}
    if arm == "SIZE_MATCHED_SHAM":
        n = max(1, len(json.dumps(full)) - len(json.dumps(base)) - 12)
        return {**base, "noninformative": "".join(random.Random(seed).choice("abcdef0123456789") for _ in range(n))}
    raise ValueError(arm)
