-- Vithia publication FCG query examples.
-- These queries are intended for the derived DuckDB generated by build_derived_fcg.py.

-- 1. Claims and current states.
SELECT claim_id, claim_state, evidence_level
FROM v_claims
ORDER BY claim_id;

-- 2. Negative/null/not-computed states are preserved.
SELECT claim_id, claim_state
FROM v_claims
WHERE claim_state IN ('NOT_SUPPORTED','FAIL_TO_REJECT_H0','NOT_COMPUTED','NOT_TESTED','NOT_COMPARABLE','UNKNOWN');

-- 3. Manuscript occurrence to evidence references.
SELECT *
FROM v_claim_evidence
ORDER BY manuscript_line, claim_id;

-- 4. Experiments and frozen input/output datasets.
SELECT experiment_id, terminal_state, input_dataset_ref, output_dataset_ref, replay_level
FROM v_experiments
ORDER BY experiment_id;

-- 5. Reused exact content across multiple occurrences.
SELECT content_fco_ref, COUNT(*) AS occurrence_count
FROM v_occurrences
GROUP BY content_fco_ref
HAVING COUNT(*) > 1
ORDER BY occurrence_count DESC;

-- 6. MMR events are custody/order evidence, not truth.
SELECT ledger_kind, sequence, breakpoint_id, mmr_size, mmr_root_after
FROM v_mmr_events
ORDER BY ledger_kind, sequence;
