#!/usr/bin/env python3
from __future__ import annotations

from getpass import getpass
from pathlib import Path
import os
import shlex

ROOT = Path(__file__).resolve().parents[2]
ENV_DIR = ROOT / ".private" / "sponsor-proof"
ENV_FILE = ENV_DIR / ".env"
KEYS = [
    "MI_API_KEY",
    "MITOSIS_API_KEY",
    "TENKI_API_KEY",
    "TENKI_AUTH_TOKEN",
    "TYPESAFE_API_KEY",
    "ANTHROPIC_API_KEY",
]

def load_existing() -> dict[str, str]:
    out: dict[str, str] = {}
    if not ENV_FILE.exists():
        return out
    for raw in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key not in KEYS:
            continue
        try:
            parts = shlex.split(value, posix=True)
            out[key] = parts[0] if parts else ""
        except ValueError:
            out[key] = value.strip().strip("'\"")
    return out

def main() -> None:
    ENV_DIR.mkdir(parents=True, exist_ok=True)
    os.chmod(ENV_DIR, 0o700)
    values = load_existing()

    print(f"SPONSOR_ENV_PATH={ENV_FILE}")
    print("Enter values securely. Input is hidden. Blank keeps an existing value or leaves the key unset.")
    for key in KEYS:
        state = "SET" if values.get(key) else "NOT_SET"
        value = getpass(f"{key} [{state}]: ")
        if value:
            values[key] = value

    lines = [
        "# Local submission credentials. NEVER COMMIT.",
        "# Generated by tools/gum_doctor_sponsor/configure_env.py",
    ]
    for key in KEYS:
        if values.get(key):
            lines.append(f"{key}={shlex.quote(values[key])}")
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(ENV_FILE, 0o600)

    print("SPONSOR_ENV=WRITTEN")
    for key in KEYS:
        print(f"{key}={'SET' if values.get(key) else 'NOT_SET'}")

if __name__ == "__main__":
    main()
